apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: postgres-operator
  labels:
    app.kubernetes.io/name: keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
      - image: bitnami/keycloak:latest
        name: keycloak
        env:
        - name: KEYCLOAK_DATABASE_VENDOR
          value: "postgresql"
        - name: KEYCLOAK_DATABASE_HOST
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: host } }
        - name: KEYCLOAK_DATABASE_PORT
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: port } }
        - name: KEYCLOAK_DATABASE_NAME
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: dbname } }
        - name: KEYCLOAK_DATABASE_USER
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: user } }
        - name: KEYCLOAK_DATABASE_PASSWORD
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: password } }
        - name: KEYCLOAK_CREATE_ADMIN_USER
          value: "true"
        - name: KEYCLOAK_ADMIN_USER
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
      restartPolicy: Always
